WEBアプリ開発1-1
h-yokoyama-eiwa/tutorial pull request #7
Opened 2022-06-06 00:00 UTC by h-yokoyama-eiwa

@hyamakawa @yanagi-m @MitsukiTanaka
WEBアプリ開発1-1の作成が完了しました。
レビューをお願いします。

2022-06-06 02:51 UTC, hyamakawa requested changes
@h-yokoyama-eiwa 

確認しました。コメントしたので対応お願いいたします。
また、下記2つをお願いしたいです。

画面の見た目を新規作成したり、変更した場合は、スクショを貼って欲しいです
GoogleAppsScriptファイルを共有ドライブの方に置いてもらいたいです（動作確認しやすいように）

2022-06-06 02:51 UTC, hyamakawa commented on web_application/appsscript.json
> +}
`no newline at end of file` の警告がでてますね、解消してください！

[なぜ行末空白削除と改行が必要なのか？](https://bottoms-programming.com/archives/indent-tab-space-and-new-line.html)

2022-06-06 02:51 UTC, hyamakawa commented on web_application/countApp.js
> +	return HtmlService.createTemplateFromFile('index').evaluate();
インデント右にずれてる？

2022-06-06 02:51 UTC, hyamakawa commented on web_application/index.html
> +    <script>
<scriptタグ＞はタグ内の最下部に定義した方がいいですね。

理由としては、HTMLは上から読み込まれるのですが、今の順番だとタグの処理が読み込まれる前に

タグ内の要素を参照している処理が読み込まれてしまい、エラーが発生する可能性があるためです。 読み込まれる順番を意識して、タグの位置を意識するといいと思いますっ！

2022-06-06 02:51 UTC, hyamakawa commented on web_application/index.html
> +        let count = document.getElementById('count').innerText;
letにしてる理由はありますか？  
後続の処理を見る限り、constでいいような気がしています。

2022-06-06 06:42 UTC, h-yokoyama-eiwa commented
@hyamakawa @yanagi-m @MitsukiTanaka
スクショと共有ドライブ格納しました。

＜スクショ＞
![image](https://user-images.githubusercontent.com/67628682/172108933-f19094d4-0a2f-4b51-a2a8-7105ef0203a3.png)

＜ドライブ＞
https://drive.google.com/drive/folders/1SPyVvCotoNYLFVfhXA7nRsmQF7OpNrX0

2022-06-11 08:14 UTC, h-yokoyama-eiwa commented on web_application/countApp.js
> +	return HtmlService.createTemplateFromFile('index').evaluate();
インデントがタブになっているからずれているように見えるんでしょうか。
タブインデントの幅をスペース4つ分から２つ分に変更してみましたが、git上は変更なし扱いになりますね。
タブインデントではなくスペースインデントにすることはできますがどうしましょうか。

2022-06-11 08:15 UTC, h-yokoyama-eiwa commented on web_application/appsscript.json
> +}
最終行に改行を入れました。
ついでにVSCodeの設定でファイルの最後に改行を入れるようにしておきました。

2022-06-11 08:17 UTC, h-yokoyama-eiwa commented on web_application/index.html
> +    <script>
＜script＞タグの位置を＜body＞タグの一番下に移動しました。

2022-06-11 08:21 UTC, h-yokoyama-eiwa commented on web_application/index.html
> +        let count = document.getElementById('count').innerText;
一つ下の行で「++count」としているため、変数の再代入をしている⇒letを使用、と判断しました。
試しにconstでやってみましたが、うまく動きませんでした。
おそらく、++countでインクリメント後の値を返すはずが、constだとインクリメントできないのでそのままの値が返っている、のではないかと思っていますがいかがでしょうか。

2022-06-11 21:13 UTC, hyamakawa commented on web_application/appsscript.json
> +}
🙆‍♂️

2022-06-11 21:13 UTC, hyamakawa commented on web_application/countApp.js
> +	return HtmlService.createTemplateFromFile('index').evaluate();
🙆‍♂️

2022-06-11 21:13 UTC, hyamakawa commented on web_application/index.html
> +    <script>
🙆‍♂️

2022-06-11 21:13 UTC, hyamakawa commented on web_application/index.html
> +        let count = document.getElementById('count').innerText;
ほんとだ、改めてみるとそうですね、頭が動いてなかったのかもしれません、ごめんなさいっ 🙇

2022-06-11 21:13 UTC, hyamakawa commented
@h-yokoyama-eiwa LGTM 🙆‍♂️

2022-06-13 07:43 UTC, h-yokoyama-eiwa commented
@yanagi-m @MitsukiTanaka
もしかしたら忘れられているかも、と思い一応もう一度メンションします。
お忙しいとは思いますが、来週前半くらいまでで確認いただけると助かります。
よろしくお願いします。

2022-06-18 07:27 UTC, merged